### ISSUE TITLE
Error: not found rules

### ISSUE THREAD

**Issue by nexcode** [cvisco/eslint-plugin-requirejs#104]
[eslint] Definition for rule 'requirejs/no-invalid-define' was not found (requirejs/no-invalid-define)
[eslint] Definition for rule 'requirejs/no-invalid-require' was not found (requirejs/no-invalid-require)
[eslint] Definition for rule 'requirejs/no-multiple-define' was not found (requirejs/no-multiple-define)
[eslint] Definition for rule 'requirejs/no-assign-exports' was not found (requirejs/no-assign-exports)
[eslint] Definition for rule 'requirejs/no-js-extension' was not found (requirejs/no-js-extension)
any

How fix it?
I use: "plugin:requirejs/recommended"

**Comment by platinumazure** [comment]
Are you using the latest version of this plugin?

Can you please show your ESLint config?

**Comment by nexcode** [comment]
eslint@4.4.1
eslint-plugin-requirejs@3.1.1
less@2.7.2
npm@3.10.10

```
{
    "env": {
        "browser": true
    },
    "extends": [
        "eslint:recommended",
        "plugin:requirejs/recommended"
    ],
    "rules": {
        "indent": [
            "error",
            4
        ],
        "linebreak-style": [
            "error",
            "unix"
        ],
        "quotes": [
            "error",
            "single"
        ],
        "semi": [
            "error",
            "always"
        ]
    }
}
```

https://yadi.sk/i/HAEj4TmW3LoK5Y

**Comment by platinumazure** [comment]
@nexcode Really sorry I didn't reply to you, I lost track of this.

You need to include the plugin in your configuration:

```js
{
    "env": {
        "browser": true
    },
    "extends": [
        "eslint:recommended",
        "plugin:requirejs/recommended"
    ],
    "plugins": ["requirejs"],
    // etc.
}
```

This will allow ESLint to find the rules that you are pulling in as a result of extending from `plugin:requirejs/recommended` configuration.
