### ISSUE TITLE
 one-dependency-per-line throws

### ISSUE THREAD

**Issue by davidsu** [cvisco/eslint-plugin-requirejs#106]
Having a file with named module like so `define('boo', [], () =>window. _);` get the following:
`TypeError: Cannot read property '0' of undefined`
because it's throwing can't even `//eslint-disable-line`, it still fails the eslint task

EDIT:
the problem is the arrow-function here, swapping it for `function(){return window._}` solves it but that's bad, it shouldn't throw

**Comment by cvisco** [comment]
Yikes. I guess we aren't supporting arrow functions as valid modules. I'll take a look at this soon.
