### ISSUE TITLE
New rule: no-restricted-requires

### ISSUE THREAD

**Issue by stefanbuck** [cvisco/eslint-plugin-requirejs#109]
Basically the same as https://eslint.org/docs/rules/no-restricted-imports, but for AMD.

**Comment by cvisco** [comment]
Yep, this could definitely be useful. Seems like there is also https://eslint.org/docs/rules/no-restricted-modules which _should_ cover the CommonJS style imports already. Only thing missing is a rule for classic AMD-style imports

**Comment by stefanbuck** [comment]
Which existing rule is a good starting point for this feature in your opinion?
