### ISSUE TITLE
New rule: amd-function-arity

### ISSUE THREAD

**Issue by ganimomer** [cvisco/eslint-plugin-requirejs#38]
The rule should make sure that when defining a module in the AMD form of define, the function should have the same length (arity) as the array.
**Example:**
valid:

``` js
define(['a', 'b'], function(a, b) { 
  // module code...
});
```

invalid:

``` js
define(['a', 'b'], function(a) {
  // module code that doesn't use b
});
```

``` js
define(['a', 'b'], function(a, b, c) {
 // c is undefined
});
```

I know in some cases requiring a dependency is used for side effects, but I think in most cases it's just a bug, so the edge cases can disable the rule for the line.

**Comment by platinumazure** [comment]
It wouldn't hurt to have an option which allows too many params (but not too few), would it? That way people could choose whether they want to allow the side effect case or not.

**Comment by cvisco** [comment]
Yea I agree this makes sense to have as a optional flag. I've definitely been involved with projects where things are often included for side effects. And in those cases we still want to verify that the dependency list is not shorter than the module definition functions arity.

**Comment by platinumazure** [comment]
I'll start on this.
