### ISSUE TITLE
package.json does not have "files" key

### ISSUE THREAD

**Issue by platinumazure** [cvisco/eslint-plugin-requirejs#40]
The `package.json` file in this repository does not have a "files" key. The result is that when installing this package as a devDependency, unit tests and documentation (and some other files) are included when they don't need to be.

It's better to just have the minimum files needed to actually run the rules (probably `lib/`, `index.js`).

**Comment by cvisco** [comment]
Good catch. I'll take a look at this.

**Comment by platinumazure** [comment]
@cvisco Are you still intending to do this, or would it help for me to write a PR?

**Comment by cvisco** [comment]
@platinumazure, I'm still traveling thru the end of the month, so I would absolutely welcome a PR for it.

**Comment by platinumazure** [comment]
Thanks. Sent a PR using the files array. If you would prefer I use
`.npmignore`, I can do that too.
