### ISSUE TITLE
node makefile.js does not work on Windows

### ISSUE THREAD

**Issue by platinumazure** [cvisco/eslint-plugin-requirejs#41]
None of the makefile tasks work on Windows by default. Some of the tasks are specified using shell commands that work in a Bash-compatible shell; ideally, these would be transformed to use Node.js paths and things like that, which would help normalize OS inconsistencies.

**Comment by cvisco** [comment]
Is this something you'd like to take a crack at ironing out?

**Comment by platinumazure** [comment]
I'm willing to give it a shot, but I don't know shelljs very well. I know eslint/eslint has figured it out, though, so hopefully I can just look there.

**Comment by cvisco** [comment]
Awesome. I'm happy to verify any changes on the MacOS side to make sure
there aren't any regressions.

**Comment by platinumazure** [comment]
Hoping to work on this tonight.
