### ISSUE TITLE
no-multiple-define message could be more useful (and rule could be faster?)

### ISSUE THREAD

**Issue by platinumazure** [cvisco/eslint-plugin-requirejs#42]
The `no-multiple-define` rule works by iterating through all tokens in a program and reporting only once at the very end if the total number of `define` identifiers is greater than 1. This results in one message at the beginning of the file. I think the rule could be more useful if it reported all violating nodes (after the first one), so that line and column information is accurate.

In addition, the rule should not need to iterate over all tokens, only CallExpressions (after all, using the identifier `define` does not always imply a module definition, such as `typeof define === "function"`). By changing the rule to run its checks on CallExpression nodes, that should make the rule a bit faster. The rule can still keep track of define calls by closing over the count variable.

I'm happy to write a PR if you accept this issue.

**Comment by cvisco** [comment]
@platinumazure. Accepted, and good call! I'll admit some of these rules were hastily written for internal use, and could definitely stand to be improved!
