### ISSUE TITLE
Feature request: Enforce dependency array length equals factory argument count

### ISSUE THREAD

**Issue by captbaritone** [cvisco/eslint-plugin-requirejs#48]
A rule where something like this would fail:

```
Define(['dep1', 'dep2'], function(dep1) {
    //...
});
```

I've seen this a few times in our code base as an artifact of somebody messing up when removing a dependency.

**Comment by platinumazure** [comment]
Duplicate of #38, implemented by #46. That should cover your use case, no?

If that looks good to you, then you just need to wait for the next minor release :smile:

**Comment by captbaritone** [comment]
Whoops! Thank you!
