### ISSUE TITLE
Making one-dependency-per-line fixable?

### ISSUE THREAD

**Issue by afahim** [cvisco/eslint-plugin-requirejs#51]
Just wanted to put this out there, are there any plans for making `one-dependency-per-line` fixable, so that it can be run with `--fix` and the dependencies are automatically formatted?

http://eslint.org/docs/user-guide/command-line-interface.html#fix

**Comment by cvisco** [comment]
I hadn't considered this, actually. I like it though. This is definitely worth a look!
