### ISSUE TITLE
Rule test coverage is low (need a few istanbul ignore directives)

### ISSUE THREAD

**Issue by platinumazure** [cvisco/eslint-plugin-requirejs#53]
If this is accepted, I can work on a pull request for adding `/* istanbul ignore else */` or `/* istanbul ignore next */` directives for some of the areas in rules identified by Istanbul as lacking coverage. (I'm fairly sure all the ones in the rules themselves can be marked with ignore directives. The ones in `lib/util.js` I'm not so sure of.)

**Comment by cvisco** [comment]
Based on what's not covered I think this is fine, but would it make sense to just add test cases for the inferred `else` clauses, etc?

**Comment by platinumazure** [comment]
When I was looking through the coverage report, I think there were a couple
of instances where I had thought that would be impossible due to the logic
of the rule, but I can certainly reexamine the report and reevaluate that
premise.

**Comment by cvisco** [comment]
Fair enough. I would say if it's possible to add a test to improve the coverage, then we should, but if its a case where it truly is not possible to add a test, we should ask ourselves if there isn't a problem with the structure of the code?

**Comment by platinumazure** [comment]
Yeah, I'll give it another look in the next couple of days.

**Comment by cvisco** [comment]
@platinumazure is this still an issue?

**Comment by platinumazure** [comment]
With coveralls saying 100% test coverage, probably not. Closing.
