### ISSUE TITLE
Consider using "requireindex" package to simplify test fixture consumption

### ISSUE THREAD

**Issue by platinumazure** [cvisco/eslint-plugin-requirejs#54]
Right now, in order to add new test fixtures, some manual work must be done (adding to `test/fixtures/index.js`, etc.). I am wondering if the "requireindex" package might be able to do some of this dynamically.

**Comment by cvisco** [comment]
I am all for cleaning up the fixture loading!

**Comment by platinumazure** [comment]
Hoping to fix this later this week. Sorry for the delay. If you or anyone else finds time and wants to have a go, feel free (I'll comment again when actually working on this).

**Comment by cvisco** [comment]
No worries, I can do this one tonight
