### ISSUE TITLE
Sort-amd-path rule should ignore some paths

### ISSUE THREAD

**Issue by obrejla** [cvisco/eslint-plugin-requirejs#63]
Paths which don't have defined their own corresponding parameter should be skipped in sorting check. They are probably at the end of the list and are just loaded because they must be preloaded. No one does anything with them, they just need to be loaded.

``` js
define([
    'foo/bar/Baz',
    'just/something/to/load/Whatever' // I just need to preload this library at this place
], function (Baz) { // no Whatever in param list, it's not needed
    /* ... */
});
```

**Comment by obrejla** [comment]
I can imho fix it... It should be simple fix, just count the number of params and use only that number of array items from dependency array.

**Comment by platinumazure** [comment]
Yes, we can't force a sort if it changes whether the module is being required for side effects or not. This sounds like a bug to me.

**Comment by cvisco** [comment]
Agreed.
