### ISSUE TITLE
Sorting of paths with a plugin prefix

### ISSUE THREAD

**Issue by obrejla** [cvisco/eslint-plugin-requirejs#73]
There should be some option what to do with path which have a plugin prefix. It doesn't look well if it is distributed across entire dependency array :)

There should be an option which should: 
- "preserve alphabetical order between other paths" (this is current behavior), 
- "push paths with plugins at start",
- "push paths with plugins at the end", or 
- "ignore plugin and sort it like it has no plugin"

Imho quire useful improvement.

**Comment by cvisco** [comment]
Let's formalize this a bit more. But, yes, good idea!

**Comment by obrejla** [comment]
Yep, my thoughts are written above, currently have nothing else to add :) Not sure what you exactly mean by formalizing, but my mind is open and I'll wait with an implementation :) So what do you mean?

**Comment by cvisco** [comment]
@obrejla, as in "what would the API look like?"

Example:

``` js
{ 
    "plugins": "sort-first" // or "sort-last", "ignore-prefix", etc.
}
```

Also, could you clarify the difference between "preserve alphabetical order between other paths" and "ignore plugin and sort it like it has no plugin"? In the first case, what happens exactly?

**Comment by obrejla** [comment]
API e.g.

``` js
{
    "sortPlugins": "preserve" // "first", "last", or "ignore"
}
```

Difference:
"preserve alphabetical order between other paths":

``` js
'aaa/aaa/aaa',
'bbb!foo/bar/baz',
'ccc/ccc/ccc',
'ggg/ggg/ggg'
```

"ignore plugin and sort like it has no plugin":

``` js
'aaa/aaa/aaa',
'ccc/ccc/ccc',
'bbb!foo/bar/baz', // plugin is ignored, so it is sorted like foo/bar/baz
'ggg/ggg/ggg'
```

**Comment by cvisco** [comment]
Got it. Thanks!

**Comment by obrejla** [comment]
You're welcome! :) Will start with impl soon...I hope..
