### ISSUE TITLE
Update ESLint Peer Dependency to 2.x

### ISSUE THREAD

**Issue by ghost** [cvisco/eslint-plugin-requirejs#76]
The peer dependency of `>=1.4.0` doesn't seem to pick up my eslint `2.2.0`, is that correct?

Which is odd because a open ended range such as `>=1.4.0` (eslint) that you use should even pick up breaking changes. Of course, we know with `eslint` these are going to throw messages at you having the old configuration.

Hence I ask you: is this suitable for use with eslint `2.x`? Any chance it will? I didn't find a alternative branch in here.

Cheers

**Comment by platinumazure** [comment]
I would assume `>=1.4.0` should pick up 2.2.0. What in particular are you seeing? Do you get the peer dependency warning?

Could you please share your node and npm versions, as well as your full package directory structure including node_modules?

**Comment by cvisco** [comment]
@robjens I'm currently using it in production with eslint 2.2.0 and have not run into any issues.

**Comment by ghost** [comment]
@platinumazure Hi, looking back (and trying again), it is indeed the PEER DEPENDENCY warning I probably referred to. But I guess this isn't so much your doing, still can you tell me why I get that warning though? I would guess it would be a npm quirk then? 

![image](https://cloud.githubusercontent.com/assets/11848802/14201070/f7a1cc40-f7de-11e5-97a7-6656546188fd.png)

Thanks a lot folks.

**Comment by platinumazure** [comment]
You installed the plugin globally, so npm will be looking for a global ESLint instance too.  If ESLint is installed locally in a project, that could be causing the issue. In general, I recommend installing both locally to make things easier.

Just to be sure, though, can you run `eslint -v`? This will tell you what version of ESLint you've installed globally, if any.

**Comment by cvisco** [comment]
I've noticed this same warning in other projects. Notably with React. I installed a React v15 release candidate and some other modules warned that it didn't satisfy the >= 0.14 range (even tho it technically should). Can't find much on the web about this but I know it's not just us.

I'm thinking we should just do a major version release soon specifically for eslint 2.x+
