### ISSUE TITLE
Improve amd-function-arity Rule: Allow only named extra dependencies

### ISSUE THREAD

**Issue by sbason** [cvisco/eslint-plugin-requirejs#77]
Instead of only excepting a boolean in the `allowExtraDependencies` property, I would like it to additionally accept an array of strings. If the unused dependency paths are contained in the `allowExtraDependencies` property array then there should be no error. 

Example for code: 

``` javascript
define([
    'aPath',
    'bPath',
    'cPath',
    'dPath'
], function (a, b, c) { 
```

Would error with the rule set as:

``` javascript
"requirejs/amd-function-arity": [2, { "allowExtraDependencies": ["ePath", "fPath", "gPath"] }]
```

``` javascript
"requirejs/amd-function-arity": [2, { "allowExtraDependencies": ["aPath", "bPath", "cPath"] }]
```

``` javascript
"requirejs/amd-function-arity": [2, { "allowExtraDependencies": false }]`
```

But would not error with the rule set as:

``` javascript
"requirejs/amd-function-arity": [2, { "allowExtraDependencies": ["dPath", "ePath", "fPath"] }]
```

``` javascript
"requirejs/amd-function-arity": [2, { "allowExtraDependencies": ["dPath", "aPath", "bPath"] }]
```

``` javascript
"requirejs/amd-function-arity": [2, { "allowExtraDependencies": true }]
```

Docs on current rule: https://github.com/cvisco/eslint-plugin-requirejs/blob/master/docs/rules/amd-function-arity.md

**Comment by cvisco** [comment]
@sbason yep, this seems sensible.
